name: spark_widgets
version: 0.0.2
author: Spark Team
description: A general purpose Polymer widget library (used by Spark IDE)
homepage: https://github.com/dart-lang/spark/
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  bootjack: '>=0.6.5 <0.7.0'
  polymer: '>=0.10.0-pre.11 <0.11.0'

dev_dependencies:
  unittest: '>=0.10.1+1 <0.11.0'
